### ISSUE TITLE
Share to the public

### ISSUE THREAD

**Issue by scrlys** [AWSWCommunity/AWSW-Modtools#7]
Unfortunately, our main source of communication has died off. We can attempt to move our conversations, but I feel it won't gather a lot of people. Rather, I'd like to open up the project to the general public through their Steam community page, social media accounts, and the unofficial Discord server.
It would be foolish to not share. With around four contributors, two of which are semi-frequent, the project cannot grow. We have no artists to draw accompaying art. We used to have a writer, but he pulled out of the project when he deleted his journal.
If no reply is gotten in a few days, I shall take measures to continue and spread word about the project.

**Comment by AWSWCommunity** [comment]
Hey, no problem. Go ahead and do what you think is best.

**Comment by scrlys** [comment]
Darn, someone beat me to it. Oh well, at least they know.
